name: Java selenimum CI

on:
  push:
    branches: [ main ]
  pull:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Selenium Tests (Headless)
        run: mvn test
