name: Java Selenium CI

# Trigger workflow on push or pull request to main
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Selenium Tests (Headless)
        run: mvn test
